### ISSUE TITLE
not seeing outside temperature and a big thank you!

### ISSUE THREAD

**Issue by snelweg** [marconfus/ha-nefit-ng#1]
Thanks for keeping this sensor up-to-date!

I noticed on the commit message that there was outside temperature monitoring? I installed the new sensor code and restarted HA.
But I do not see the outside temperature in my dashboard. What am I doing wrong?

**Comment by marconfus** [comment]
Outside temperature is not very useful, but it was in the old component so I added it. 
I guess if you added you location in the app, it will query a weather service (which can be done in homeassistant much better).
It's a climate component so it doesn't expose any sensors. The extra information is in the state attributes. I have added some information to the readme how you can configure a template sensor to get that data.

**Comment by snelweg** [comment]
aha, ok thank you.
