### ISSUE TITLE
integration error after update 0.92 + fix

### ISSUE THREAD

**Issue by bywilco** [marconfus/ha-nefit-ng#14]
nefit component gives integration error.
fix:
Due to this 27, you need to create empty file **__init__.py** and **manifest.json** in the folder custom_components/{your_platform} with content like this:

`{
  "domain": "your_domain_name",
  "name": "Your Intgration",
  "documentation": "https://www.example.com",
  "dependencies": [],
  "codeowners": [],
  "requirements": []
}`

**Comment by marconfus** [comment]
manifest.json added to repository.
