### ISSUE TITLE
As of HA 0.96.0 this component does not work anymore

### ISSUE THREAD

**Issue by harryd100** [marconfus/ha-nefit-ng#17]
As of HA 0.96.0 this component does not work anymore due to major changes in the climate integration. Are there any plans to change this?

**Comment by puk1966** [comment]
Well, it's more compatible with Alexa/Google now... Well done Home Assistant :(

**Comment by ghost** [comment]
Some constants and procedure names have changed in the new HA climate component . I modified the custom nefit climate.py file and have a working beta version now :) 
Works for my Nefit Easy thermostat in HASSIO 0.96 and I like to share the modified version with you.

@marconfus : Can you have a look (review) at modified climate.py code ?
                         Hope it will save you time to solve this issue.

Modified climate.py for 0.96 --> [climate.txt](https://github.com/marconfus/ha-nefit-ng/files/3414483/climate.txt)
 
Installation instructions are below. 
Only perform it if you know what you're doing and how to restore changes in case of issues:

```
1. Make a backup (snapshot) of your current HA first. 
2. Rename config/custom_components/nefit/climate.py file to climate_old.py.
3. Download above climate.txt file, rename it to climate.py and copy it under your 
    config/custom_components/nefit folder.
4. Check your HA configuration under menu "Configuration, General, Check config" . 
    Result should be "Configuration valid!".  
    NOTE: In HA 0.96 you need to enable the "Check config" function (it's disabled as of version 0.96)  
5. Restart HA twice (after updating to HA 0.96 the "\HASSIO\config\deps\lib\python3.7\site-packages" 
    folder is empty. Required packages will be downloaded after 2nd restart.
```

Good luck

**Comment by bywilco** [comment]
tried your file. but still the error:
Timeout while connecting to Bosch cloud. Retrying in the background

**Comment by puk1966** [comment]
@bywilco 

Check if you have the required "manifest.json" file under you "config/custom_components/nefit" folder.
If not then copy it there (see instruction on how to install custom nefit copmponent).

Also, after updating to HA 0.96 the next folder is empty:
   "\HASSIO\config\deps\lib\python3.7\site-packages". 

You need to restart HA twice, the second time the required site-packages are downloaded.
Also see this issue for more info-->

**Comment by ksya** [comment]
It works with 0.96 now.

**Comment by sbesteman** [comment]
Confirmed it works on version 0.96.4. Had to upgrade from 0.93.2 to get it working
