### ISSUE TITLE
Boiler indicator

### ISSUE THREAD

**Issue by alextud** [marconfus/ha-nefit-ng#2]
Hey, thanks for library and the effort in creating this library.

I have one small request, can you add back boiler status.

**Comment by marconfus** [comment]
It's there as the unparsed value in the state attribute boiler_indicator_raw.
 "CH"=central heating; "HW"=hot water; "No"=off

**Comment by alextud** [comment]
I assumed that No == not working. Thanks

**Comment by marconfus** [comment]
No 😄
