### ISSUE TITLE
Platform not found: climate.nefit

### ISSUE THREAD

**Issue by demich89** [marconfus/ha-nefit-ng#3]
So I created in the directory config the flowing:
custom_components > climate > nefit.py

in my configuration.yaml I put in this code:

climate:
   platform: nefit
   name: Heating
   serial: 'xxxx'
   accesskey: 'xxxxx'
   password: 'xxxxxx'

But everytime i get the error while checking config:

Platform not found: climate.nefit

**Comment by marconfus** [comment]
Have you restarted or only checked the config?

**Comment by demich89** [comment]
Yes also restarted everything

**Comment by marconfus** [comment]
It seems as Homeassistant doesn't find the code at all. Sure that the nefit.py has the right content?
If you use the wrong URL to download this sometimes happens.

**Comment by demich89** [comment]
I removed the script and added it again. Now it's working. Thank you for support!
