### ISSUE TITLE
nefit: Error on device update!

### ISSUE THREAD

**Issue by ghost** [marconfus/ha-nefit-ng#4]
NOTE: I use hassio on rasp pi 3b+ (HassOS 1.13, Home Assistant 0.86.4 latest version).
Followed instructions (copied nefit.py to the specified directory, added climate section in config file with correct serialnr, access and pwd) but get errors below in logging after rebooting Hass:

**nefit: Error on device update!**
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 347, in async_device_update
    await self.async_update()
  File "/config/custom_components/climate/nefit.py", line 173, in async_update
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Log Details (WARNING)**
Setup of platform nefit is taking over 10 seconds.

**Log Details (WARNING)**
Using slower stringprep, consider compiling the faster cython/libidn one.

**Comment by marconfus** [comment]
The device is not answering to the Bosch servers... Is the thermostat connected to the internet? Is the mobile app working?

**Comment by ghost** [comment]
Hi marconfus,

Thanks for your prompt reply :)
The thermostat (Nefit Easy) is connected to the internet, the mobile app from Nefit is working fine on my Ipad. From some search in the Github forums I understand that the thermostat communicates through Bosch server, so the thermostat cannot be addressed directly, it needs the Bosch server. Is that correct ?
In older/other posts I see that a Nefit HTTP Server (made by Robert Klep) was needed, is this not needed anymore ?

**Comment by ghost** [comment]
I have some extra information after debugging this issue:

I deliberately changed my Nefit password in the config file into a wrong one, and now I get a password error in the logging after restarting HASS. This means that there IS indeed communication with the thermostat/Bosch server. So that's a good sign. Changed password back again to correct value in config file..

After that I deliberately changed the accesskey and I get other errors (No appropriate login method. Platform nefit not ready yet. Retrying in 30 seconds.) After that corrected it again in the config file.

At last I changed serialnr in a wrong one in my config file. Get again same error (No appropriate login method. Platform nefit not ready yet. Retrying in 30 seconds.)

Changed config for nefit back to correct values (like it was in the beginning) in my config file and restared HASS again......

After reboot I get the same errors again as below
I guess communication is OK, but something else goes wrong. Any ideas ???


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 347, in async_device_update
    await self.async_update()
  File "/config/custom_components/climate/nefit.py", line 173, in async_update
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

Conclusion: Comminication with the Nefit Easy works threough the network, else HASS would not give password error (or other errors). What else could be wrong ?

**Comment by marconfus** [comment]
Yes, you don't need any external components. The mobile app or this component talks to the thermostat "thru" the Bosch servers. The error you posted shows that the device is not answering.
Strange.

You could increase the loglevel and paste the full output here:

```
logger:
  default: info
  logs:
    custom_components.climate.nefit: debug
    aionefit: debug
```

**Comment by ghost** [comment]
Hi marconfus,

I will try this tomorrow. Thanks in advance for your help....

**Comment by ghost** [comment]
I added the logger, but after reboot I didn't see any error in the log.... strange.... I removed the logger and still no errors in the log after reboot ?!? So I checked my entities under "States" and climat.heating is there now :) So it works. Very strange cause I didn't change the config anymore since yesterday.
Thanks for your help, will the Nefit Easy component become official soon ?

**Comment by marconfus** [comment]
Hm, there was no connection from your thermostat to the Bosch servers. I see this quite often in my setup. That's why I asked if the official app works. Because normally then it doesn't get a connection either...

Biggest problem with making it official is choosing a good name, as Nefit Easy is only the name in the Netherlands (I think). Here in Germany it's called Junkers Control CT100.
Also I have to make some more code cleanups. In the current state it surely won't get accepted...

**Comment by ghost** [comment]
Did you see my comment about where I changed my Nefit password ? Yesterday I changed my Nefit password in the hass config file delibarately in a wrong password, I got wrong password error in the log after rebooting hass. So there was communication through the Bosch server. Looks like something else was wrong. I keep monitoring the issue and if I get the errors again I will enable the debug logging and let you know. Thanks

**Comment by marconfus** [comment]
Yes. The password is checked on the Bosch servers. If you can successfully connect to them it doesn‘t mean you can reach your thermostat. Technically it‘s a chatroom where the thermostat and the client meet.
